print_freq: 10
save_freq: 5
name: 'exp'
log_tb: True
wandb_user: nihansen
wandb_project: pretraining
ckpt_dir: '/checkpoint/nihansen/pretraining/${logging.name}/checkpoints/'
tb_dir: '/checkpoint/nihansen/pretraining/${logging.name}/tblogs/'
submitit_dir: '/checkpoint/nihansen/pretraining/${logging.name}/submitit_train_logs/'
result_dir: '/checkpoint/nihansen/pretraining/${logging.name}/results/' 
eval_freq: 5
suffix: ''
visualize: False
