name: ego4d_ssl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - compilers
  - cupy
  - libjpeg-turbo
  - pkg-config
  - opencv
  - python=3.8
  - pytorch=1.11.0
  - numba
  - torchvision=0.12.0
  - pip:
    - ffcv
    - tensorboard
    - hydra
    - submitit
    # - hydra-fair-cluster
